import { Navbar } from '@components/navbar'
import ThemeProvider from '@components/theme-provider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <Navbar />
          <main className='flex min-h-screen flex-col items-center justify-center'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
